// Sprite runtime (generated by Lussa). Load + draw generated sprites correctly.
// A sheet is a horizontal strip of SQUARE frames; the frame count is derived from the
// image, never hardcoded. SVGs and single images are drawn whole. On-screen size is the
// "size" you pass — NOT the asset's pixel resolution.

export interface SpriteSheet {
  img: HTMLImageElement;
  frameW: number;
  frameH: number;
  frameCount: number;
  isSvg: boolean;
  animations?: Record<string, { from: number; to: number; fps: number }>;
}

/** Load a sprite image (+ its optional .json sidecar of animation ranges). */
export async function loadSprite(src: string): Promise<SpriteSheet> {
  const clean = src.split('?')[0];
  const isSvg = clean.toLowerCase().endsWith('.svg');
  const img = await new Promise<HTMLImageElement>((resolve, reject) => {
    const i = new Image();
    i.onload = () => resolve(i);
    i.onerror = reject;
    i.src = src;
  });
  const frameH = img.height;
  const frameW = isSvg ? img.width : img.height; // square frames for strips
  const frameCount = isSvg ? 1 : Math.max(1, Math.round(img.width / img.height));
  let animations: SpriteSheet['animations'];
  if (!isSvg) {
    const jsonPath = clean.toLowerCase().endsWith('.png') ? clean.slice(0, -4) + '.json' : clean + '.json';
    try {
      const res = await fetch(jsonPath);
      if (res.ok) { animations = (await res.json()).animations; }
    } catch (_e) { /* no sidecar — fine */ }
  }
  return { img, frameW, frameH, frameCount, isSvg, animations };
}

export interface DrawOpts {
  x: number;
  y: number;
  size: number; // on-screen WIDTH in px (height scales by the frame aspect)
  frame?: number;
  fps?: number;
  elapsed?: number; // ms since start; drives sheet frames AND procedural anims
  angle?: number;
  flipX?: boolean;
  flipY?: boolean;
  anim?: 'flap' | 'spin' | 'bob' | 'pulse'; // PROCEDURAL animation of a single image
}

/**
 * Draw a sprite at an on-screen size. A SINGLE image is brought to life with "anim"
 * (flap/spin/bob/pulse) driven by "elapsed" — the reliable way to animate, since the
 * image model can't make clean sprite sheets. Real multi-frame sheets still play by
 * frame/fps. Also rotates (angle, e.g. by velocity) and flips (flipX to face left).
 */
export function drawSprite(ctx: CanvasRenderingContext2D, s: SpriteSheet, o: DrawOpts): void {
  const w = o.size;
  const h = o.size * (s.frameH / s.frameW);
  let f = o.frame ?? 0;
  if (o.frame == null && o.fps && o.elapsed != null && s.frameCount > 1) {
    f = Math.floor(o.elapsed / (1000 / o.fps)) % s.frameCount;
  }
  f = Math.max(0, Math.min(s.frameCount - 1, f));
  const sx = f * s.frameW;

  const t = (o.elapsed || 0) / 1000;
  let angle = o.angle || 0;
  let scaleX = o.flipX ? -1 : 1;
  let scaleY = o.flipY ? -1 : 1;
  let dy = 0;
  if (o.anim === 'flap') { scaleY *= 1 + 0.16 * Math.sin(t * 16); angle += 0.10 * Math.sin(t * 16); }
  else if (o.anim === 'spin') { angle += t * 6; }
  else if (o.anim === 'bob') { dy = -0.10 * h * Math.sin(t * 6); }
  else if (o.anim === 'pulse') { const p = 1 + 0.10 * Math.sin(t * 7); scaleX *= p; scaleY *= p; }

  ctx.save();
  ctx.translate(o.x + w / 2, o.y + h / 2 + dy);
  if (angle) { ctx.rotate(angle); }
  ctx.scale(scaleX, scaleY);
  ctx.drawImage(s.img, sx, 0, s.frameW, s.frameH, -w / 2, -h / 2, w, h);
  ctx.restore();
}

/**
 * Draw a scrolling background: the image is scaled to COVER the canvas height and
 * tiled horizontally, offset by scrollX, so it loops endlessly. Generated
 * backgrounds are mirror-doubled, so tiling has NO seam. Use this for parallax /
 * side-scroller backgrounds instead of drawing the image once (which leaves a seam).
 */
export function drawBackground(
  ctx: CanvasRenderingContext2D,
  s: SpriteSheet,
  scrollX: number,
  canvasW: number,
  canvasH: number,
): void {
  const scale = canvasH / s.img.height;
  const tileW = s.img.width * scale;
  if (tileW <= 0) { return; }
  let x = -(((scrollX % tileW) + tileW) % tileW);
  for (; x < canvasW; x += tileW) {
    ctx.drawImage(s.img, x, 0, tileW, canvasH);
  }
}

/** Stateful animation playback (uses the sidecar ranges when present). */
export class Sprite {
  sheet: SpriteSheet;
  frame = 0;
  private anim = '';
  private loop = true;
  private t = 0;
  constructor(sheet: SpriteSheet) { this.sheet = sheet; }
  private range() {
    return (this.sheet.animations && this.sheet.animations[this.anim]) || { from: 0, to: this.sheet.frameCount - 1, fps: 10 };
  }
  play(name: string, loop = true): void {
    if (this.anim !== name) { this.anim = name; this.t = 0; this.frame = this.range().from; }
    this.loop = loop;
  }
  update(dtMs: number): void {
    const r = this.range();
    this.t += dtMs;
    const step = 1000 / (r.fps || 10);
    while (this.t >= step) {
      this.t -= step;
      this.frame = this.frame >= r.to ? (this.loop ? r.from : r.to) : this.frame + 1;
    }
  }
  draw(ctx: CanvasRenderingContext2D, x: number, y: number, size: number, angle = 0): void {
    drawSprite(ctx, this.sheet, { x, y, size, frame: this.frame, angle });
  }
}
